### ISSUE TITLE
Marvelous

### ISSUE THREAD

**Issue by Marthith** [ares-emu/ares#1]
just wanted to report that marvelous is broken in ares. 

thanks for everything. great n64 core! hope you are doing good.

**Comment by near-san** [comment]
Thank you very much for your bug report. I will look into the issue.

**Comment by near-san** [comment]
Marvelous runs here. It appears you might have a bad ROM, sorry.

![marvelous](https://user-images.githubusercontent.com/77224854/109341059-dbbc0980-7837-11eb-923c-6c7a691a01d3.png)

**Comment by near-san** [comment]
Oh! I found what you meant. The performance profile has some scanlines that are off near the textbox.
Sorry, I forget that I default to the accuracy profile here. I'll look into this when I have some time.

**Comment by near-san** [comment]
This is now fixed for real ^-^;
I wasn't considering the overscan setting in the scanline widths table.
Will be fixed in the next release, thanks again!
