### ISSUE TITLE
SEGA Mega-Drive - Golden Axe II: Some of the game graphics displayed incorrectly

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#10]
NAME: Golden Axe II
REGION: WORLD (JUE)
SHA-1: 31F12A21AF018CDF88B3F2170AF5389B84FBA7E7
CRC32: 725E0A18
MD5: 2CD3573172961FA52F622F14CCFF4E1A
ARES VERSION: 118

Some of the graphics displayed incorrectly before starting the game.
See attached images.

![MD+GX_INTRO](https://user-images.githubusercontent.com/78635953/110216852-1cf88d00-7eba-11eb-8070-660b657a27a2.png)
![MD+GX](https://user-images.githubusercontent.com/78635953/110216840-05210900-7eba-11eb-91c1-e41af20e89e9.png)

**Comment by near-san** [comment]
This is fixed as of v119.3. The io.command/address bits should be set even when writing to a VDP register.
Many many thanks to EkeEke for the fix.

**Comment by Yotamtamtam** [comment]
Thank you! and EkeEke for the fix!
