### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by absolutelynothinghere** [ares-emu/ares#102]
There are no build instructions available with the source, how do I compile ares (for linux)?

**Comment by Screwtapello** [comment]
Run `make` in the `lucia` directory. You'll need a C++ compiler and various development headers; on a Debian-based system (Ubuntu, Mint, etc.) you can install these with:

    sudo apt-get install build-essential libgtk2.0-dev libpulse-dev mesa-common-dev libcairo2-dev libsdl2-dev libxv-dev libao-dev libopenal-dev libudev-dev

**Comment by absolutelynothinghere** [comment]
Thank you, works great.
