### ISSUE TITLE
SEGA Mega-Drive - Micro Machines: Black section next to the game graphics

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#11]
NAME: Micro Machines
REGION: Europe
SHA-1: 6C822AB42A37657AA2A4E70E44B201F8E8365A98
CRC32: 7FFBD1AD
MD5: BDD8341F55F01202A48FCDDF5BF80FF7
ARES VERSION: 118

The game graphics tend to the left side while on the right side of the screen there is a black part
See attached images.

![MD_MM_01](https://user-images.githubusercontent.com/78635953/110217134-1dddee80-7ebb-11eb-9d61-72d6e8977520.png)
![MD_MM_02](https://user-images.githubusercontent.com/78635953/110217135-1e768500-7ebb-11eb-92d7-6fe10be0010a.png)

**Comment by near-san** [comment]
Same bug as Lunar, it's fixed now.
