### ISSUE TITLE
SEGA Mega-Drive - Bonanza Bros: Black section next to the game graphics

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#13]
NAME: Bonanza Bros
REGION: Europe
SHA-1: CE46F2B53988F06E0BDFAAD1B0DC3E9CA936E1E8
CRC32: ADF6476C
MD5: 9C6B56E9916AADEE638F93C7F4BB1E20
ARES VERSION: 118

The game graphics tend to the left side while on the right side of the screen there is a black part
See attached image

![MD_BB](https://user-images.githubusercontent.com/78635953/110218532-ee32e480-7ec2-11eb-97f4-ed98ba4cbd4e.png)
.

**Comment by near-san** [comment]
Same issue as Lunar, fixed now.
