### ISSUE TITLE
Mac 1.16.4

### ISSUE THREAD

**Issue by Kojabi** [ares-emu/ares#14]
Latest 1.12.2 Ares works perfectly on Mac, with no problem however the latest 1.16.4 version does not, It doesn't show the text in the GUI, however it works if you just configure with the GUI in 1.12.2 and then use the config folder in 1.16.4.

**Comment by Screwtapello** [comment]
Are you sure this is the correct "ares" project? This repository is for ares the multi-platform game console emulator, whose latest version is v115, not 1.16.4.

**Comment by near-san** [comment]
Wrong project.
