### ISSUE TITLE
SEGA Mega-Drive - Mick & Mack as the Global Gladiators: Black section next to the game graphics

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#16]
NAME: Mick & Mack as the Global Gladiators
REGION: USA
SHA-1: 4FD2818888A3C265E148E9BE76525654E76347E4
CRC32: 40F17BB3
MD5: C39FE061955784A4625255F4D04084C6
ARES VERSION: 118

The game graphics tend to the left side while on the right side of the screen there is a black part
See attached images

![Mick Mack_01](https://user-images.githubusercontent.com/78635953/110219035-8b8f1800-7ec5-11eb-9576-986129390ff6.png)
![Mick Mack_02](https://user-images.githubusercontent.com/78635953/110219037-8c27ae80-7ec5-11eb-9722-37a8da462a45.png)

**Comment by near-san** [comment]
Same bug as Lunar, fixed now.
