### ISSUE TITLE
SEGA Mega-Drive - Teenage Mutant Ninja Turtles - Tournament Fighters: Some graphics displayed incorrectly

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#17]
NAME: Teenage Mutant Ninja Turtles - Tournament Fighters
REGION: JAPAN
SHA-1: 5BE86D03ABDB49B824104E9BBF0AC80023E4908C
CRC32: 8843F2C9
MD5: 1A72E14977672C6FB1CDBC5A50D8C4A2
ARES VERSION: 118

Some of the game graphics displayed incorrectly:
1) Green frames around the text
2) The shadow of the players is displayed in the wrong color
See attached images.

![MD_T1](https://user-images.githubusercontent.com/78635953/110219287-fd1b9600-7ec6-11eb-9af9-8f2181d475c6.png)
.
![MD_T2](https://user-images.githubusercontent.com/78635953/110219289-fe4cc300-7ec6-11eb-82c8-018de75957ef.png)

**Comment by Yotamtamtam** [comment]
Still exists in version v119.

**Comment by near-san** [comment]
I fixed this by undoing overly aggressive optimizations in the scanline renderer. 1.6% speed hit, but infinitely cleaner code that I can actually reason about. Worth it.

**Comment by Yotamtamtam** [comment]
Thank you!
