### ISSUE TITLE
N64 audio working sporadically on Linux build. 

### ISSUE THREAD

**Issue by cglmrfreeman** [ares-emu/ares#2]
Greetings, big fan.

I recently compiled Ares to try out the N64 emulation as I have been excited to do so for some time.

I am running into an inconsistent issue with the audio, however. It seems if the framerate locks at 60, the audio plays fine. Any rate higher than that, I get very choppy audio. In fact the recording tool I used to capture two clips of the emulator doesn't even seem to pick up the audio as I heard it, but for some reason omits the choppy sound.

I understand that the N64 cores are a work in progress and there's bound to be known issues, but I couldn't find any list, so I am reporting this as a "just in case"

https://user-images.githubusercontent.com/9744201/109408784-a4398400-7941-11eb-9969-897d24d9c6c3.mp4

https://user-images.githubusercontent.com/9744201/109408786-a8fe3800-7941-11eb-8f1a-7dc0498390c1.mp4

System specs:

- OS: openSUSE 20210223
- Kernel: x86_64 Linux 5.10.16-1-default
- DE: KDE 5.79.0 / Plasma 5.21.0
- CPU: AMD Ryzen 7 3800X 8-Core @ 16x 3.9GHz
- GPU: GeForce RTX 2060

**Comment by near-san** [comment]
Hello, can you go to Settings->Drivers/Advanced, and try increasing the audio latency? If that doesn't work, can you try other audio drivers and also increase their latency?

**Comment by cglmrfreeman** [comment]
Are... are you a wizard?

I haven't tested all possible combinations yet, but yeah, that did seem to fix the issue. When I get a free moment I'll test all the possible combinations and report back here to see if we can find a theme with them, then maybe if other Linux users have the same issue with the lower latencies, maybe it shouldn't be an option? Just spitballing here, not saying it should for sure be removed, as you probably put it there for a reason.

**Comment by near-san** [comment]
I do what I can, glad it helped ^-^
