### ISSUE TITLE
 SEGA Mega-Drive - Jim Power - The Arcade Game (Proto): Black section next to the game graphics

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#20]
NAME: Jim Power - The Arcade Game (Proto)
REGION: USA
SHA-1: 38ADC1F792B06637E109D4B76FBFBF57623FAF3B
CRC32: 1CF3238B
MD5: 4AC093AB296AD0BFF229431EB2BC6EA6
ARES VERSION: 118

The game graphics tend to the left side while on the right side of the screen there is a black part
See attached image

![J1](https://user-images.githubusercontent.com/78635953/111843806-79bc6480-890a-11eb-8c3d-947199ceb2fe.png)

**Comment by near-san** [comment]
Same bug as Lunar, fixed now.
