### ISSUE TITLE
SEGA Mega-Drive - Krusty's Super Fun House (Rev A): Black section next to the game graphics

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#21]
NAME: Krusty's Super Fun House (Rev A)
REGION: USA
SHA-1: 6AA026E394DBA0E5584C4CF99AD1C166D91F3923
CRC32: 56976261
MD5: 8BD4D2F51F08380A1BA9AC6CD2070585
ARES VERSION: 118

The game graphics tend to the left side while on the right side of the screen there is a black part
See attached images

![J1](https://user-images.githubusercontent.com/78635953/111844326-7ecde380-890b-11eb-9b17-17e7e93c0ca5.png)
![J2](https://user-images.githubusercontent.com/78635953/111844329-7f667a00-890b-11eb-97dc-85e120a1441a.png)

**Comment by near-san** [comment]
Same bug as Lunar, fixed now.
