### ISSUE TITLE
SEGA Mega-Drive - Zero the Kamikaze Squirrel: Black section next to the game graphic intros

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#22]
NAME: Zero the Kamikaze Squirrel
REGION: USA
SHA-1: DB110FA33C185A7DA4C80E92DBE4C7F23CCEC0D6
CRC32: 423968DF
MD5: 4E18827F7DD6CA39970A2EF0E0FA21D0
ARES VERSION: 118

The game graphic intros tend to the left side while on the right side of the screen there is a black part.
When the first stage begins - the black part-screen bug disappears.
See attached image

![Z1](https://user-images.githubusercontent.com/78635953/111845502-a6be4680-890d-11eb-844c-b72586bfcbaf.png)
![Z11](https://user-images.githubusercontent.com/78635953/111845506-a8880a00-890d-11eb-8def-ac8ca7c2bd95.png)
![Z111](https://user-images.githubusercontent.com/78635953/111845508-a920a080-890d-11eb-90a2-29f3080dff04.png)
![LAST](https://user-images.githubusercontent.com/78635953/111845505-a756dd00-890d-11eb-8853-0fe058137263.png)

**Comment by near-san** [comment]
Same bug as Lunar, fixed now.
