### ISSUE TITLE
SEGA Mega-CD - Lunar - The Silver Star: Black section next to the game graphics

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#29]
NAME: Lunar - The Silver Star
REGION: USA
ARES VERSION: 118

Black section next to the game graphics
See attached image
![L_TSS](https://user-images.githubusercontent.com/78635953/111882884-b77bc480-89c0-11eb-9e16-5ffeef857918.png)
.

**Comment by near-san** [comment]
This is something to do with my fast VDP renderer not working very well. I'll attempt to fix it, but may need to fall back to my dot-based renderer (it's slower) for ares v119. Thank you for reporting the issue.

**Comment by near-san** [comment]
I've fixed this issue, it will work correctly in the next release with the fast scanline renderer.

**Comment by Yotamtamtam** [comment]
Awesome! Thank you very much 👍
