### ISSUE TITLE
Minigame timers in Majora's Mask run two times faster than usual

### ISSUE THREAD

**Issue by itsbirdseed** [ares-emu/ares#3]
The numbered counters used in minigames, like Deku Playground and the Postman's training game, seem to run twice as fast. The 72 hour clock runs fine, and Zora diving minigame timer on the OoT debug ROM doesn't appear to share the issue.

Here's my system info, in case it's relevant:
[DxDiag.txt](https://github.com/ares-emu/ares/files/6056301/DxDiag.txt)

(Thank you, by the way! I very much respect you and your work.)

**Comment by near-san** [comment]
There's a 50/50 chance this will be fixed in the next release, ares v119. I was running one of the counters at 2X speed. But it didn't resolve Namco Museum's F1 Pole Position running too fast, so I'm not sure if it'll fix Majora's Mask or not yet.

**Comment by near-san** [comment]
@itsbirdseed or anyone else, can you test this now with ares v119 please? Fingers crossed.

**Comment by itsbirdseed** [comment]
Did a quick test on v119, seems like it did the trick!

**Comment by near-san** [comment]
Hell yeah! Thanks so much!
