### ISSUE TITLE
Nintendo Famicom - General: Ares does not display the whole games bottom screen garphics 

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#35]
I suspect ares does not display all the bottom screen graphics according to the video resolution.

In a previous post I reported a graphic bug for the game DuckTales. I think that it was caused by the same reason of this report.
See attched two images for more clear explanation:
One shows how a certain game is displayed in ares and the second show how it should be displayed

![LS](https://user-images.githubusercontent.com/78635953/112743702-4466e500-8fa2-11eb-9837-2aef04926654.png)
![LS2](https://user-images.githubusercontent.com/78635953/112743705-45981200-8fa2-11eb-959e-ae65d247237b.png)

**Comment by Screwtapello** [comment]
In Settings → Video, is the "Overscan" option enabled?

**Comment by Yotamtamtam** [comment]
Thank you!
I was not aware of this possibility - It sorted out the issue.
Definitely not a bug
