### ISSUE TITLE
SEGA Mega-CD - General: Ares preform exit operation when loading any sega-cd game

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#36]
Ares preform exit operation when loading any sega-cd game

Tested on Ares v119 on Microsoft Windows 10 Home
Version: 10.0.19042 Build 19042
Inspirion 7577. x64 based PC
I7-7700hq @ 2.80 GHz

**Comment by HeroponRikiBestest** [comment]
Confirmed issue.

Tested on Ares v119 on Linux Mint 20
Lenovo Thinkpad T440s. x64 based PC.
i7-4600U CPU @ 2.10GHz

**Comment by near-san** [comment]
I see what happened, I didn't check for no cartridge being present when sending the 32X vblank/hblank signals. It will be fixed in v119.1 that I will release in a day or two. Sorry about that.

**Comment by Yotamtamtam** [comment]
Thank you 👍
