### ISSUE TITLE
WonderSwan Color - General: Games no longer have music & sounds

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#37]
On Ares 119 WonderSwan Color Games no longer have music & sounds 

Tested on Ares v119 on Microsoft Windows 10 Home
Version: 10.0.19042 Build 19042
Inspirion 7577. x64 based PC
I7-7700hq @ 2.80 GHz

**Comment by near-san** [comment]
I fixed it. WSC internal EEPROM was the wrong size, and I was overwriting the initialization data when the file didn't exist on disk. I'll release v119.1 soon to correct this.

**Comment by Yotamtamtam** [comment]
Thank you very much! :)
