### ISSUE TITLE
SEGA Mega-Drive - Earth Worm Jim: Graphics displayed incorrectly

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#4]
NAME: Earth Worm Jim
REGION: USA
SHA-1: A544211D1EBAB1F096F6E72A0D724F74F9DDBCE8
CRC32: DF3ACF59
MD5: 074DCF012F3FD11A4C7E624474944D81
ARES VERSION: 118

The graphics are displayed incorrectly in game mode.
See attached image.
![EWJ1](https://user-images.githubusercontent.com/78635953/110213960-0a2a8c00-7eab-11eb-80d1-f67851e880d0.png)
PS: Thank you for the investment and contribution to the community. You're a star and inspiration for me :)

**Comment by near-san** [comment]
Is there a way I can ping you outside of GitHub?
I'd like to send you a build with the accuracy-based VDP renderer so we can narrow these bugs down a bit more.
The scanline renderer clearly has some major issues that need to be fixed, though.

**Comment by Yotamtamtam** [comment]
Yes, Of course. I would be happy to assist in any way possible.
You can pm me at yotamtampm@gmail.com

**Comment by Yotamtamtam** [comment]
Fixed on Ares v119.
