### ISSUE TITLE
Native save files don't work

### ISSUE THREAD

**Issue by Tasosgemah** [ares-emu/ares#40]
I only tried a couple of N64 games but it appears the emulator doesn't create the save files when i use the native save function. I changed the save paths and still doesn't save.

I'm using Windows 10.

**Comment by near-san** [comment]
I think there's a problem when save paths are set. Please try not having a save path set. I will try to fix this right away.

**Comment by near-san** [comment]
It was indeed broken, but only when a manual path was selected. I will release a v119.1 bugfix build later today or tomorrow. My apologies.

    saveLocation = {path, this->name(), "/", Location::prefix(location), extension};

**Comment by Yotamtamtam** [comment]
I predefined the save files folder and tried several systems, Mega Drive, Super Nintendo and Nintendo 64.
All seems to work. I did only tried to save and load throught the emulator native menues (throught Slot 1)

**Comment by near-san** [comment]
v19.2 is out now.

**Comment by Tasosgemah** [comment]
> 
> 
> v19.2 is out now.

Thanks, it works.

However, it generates a .eeprom file. This seems different than other emulators like Mupen, PJ64 and RetroArch. The program i use to convert files also doesn't seem to recognize it. Is there another way to use my completed saves with Ares?
