### ISSUE TITLE
[sfc] Rectangular world map does not render in Secret of Mana (USA)

### ISSUE THREAD

**Issue by Screwtapello** [ares-emu/ares#41]
Originally filed as https://github.com/higan-emu/higan/issues/170

### Steps to reproduce

- Use the SRAM file linked from [this comment](https://github.com/higan-emu/higan/issues/170#issuecomment-811068403)
- Boot the game, load the (only) save
- Go south to exit the building
- Press X to open the ring menu
- Press Up to switch the menu to "items" mode
- Press Right a few times to cycle around to the "Flammie Drum" item (looks like a [pellet drum](https://en.wikipedia.org/wiki/Pellet_drum) or a lollipop)
- Press A to activate the item, and watch a cutscene where you get snatched into the air by a dragon, something like this:

    ![dragon flying in the air](https://user-images.githubusercontent.com/1450918/113251277-bece9680-930d-11eb-8503-ca6c18f1f656.png)

- Press Start to view the world map as a sphere:

    ![spherical world map](https://user-images.githubusercontent.com/1450918/113251554-33a1d080-930e-11eb-8ccd-43068587318c.png)

- Press R to switch to a rectangular projection

### Expected result

The map slowly renders, then eventually looks like this (with a blinking cursor not pictured here):

![rectangular world map](https://user-images.githubusercontent.com/1450918/113251634-58964380-930e-11eb-97c6-366cf8ec1e54.png)

(this screenshot taken from higan)

### Actual result

The game shows a black screen for a few seconds, and then the blinking cursor appears in the void.

**Comment by near-san** [comment]
Thank you for the bug report!

The problem was the argument order was wrong in the direct color lookup, it should be like so:

    mosaicColor = ppu.dac.directColor(mosaicPalette, paletteNumber);

It is fixed as of v119.1 now.

**Comment by near-san** [comment]
v119.2 is out now.
