### ISSUE TITLE
Support for Zip files [Feature Request]

### ISSUE THREAD

**Issue by a7mag3ddon** [ares-emu/ares#42]
Hello,

Not really an issue but a feature request, Please can you add support for .zip files for roms, most other emulators support decompressing on the fly and would be really helpful if you could.

One major benefit of this would be that you can play games from a repository on your computer and not have to keep 2 sets of roms files one compressed the other not.

THANKS

**Comment by near-san** [comment]
I do support ZIP files. Can you elaborate on what's not working for you, please?

**Comment by a7mag3ddon** [comment]
Very sorry please close the issue.

I just realised my coleco roms are all .gz but they show with winzip icon and i did not see.
