### ISSUE TITLE
Some drivers don't load on Archlinux v119

### ISSUE THREAD

**Issue by Mastergatto** [ares-emu/ares#43]
Currently using Archlinux and GNOME, what I have done is:
1. I downloaded v119 from ares.dev and extracted it
2. cd ./ares_v119/lucia
3. make hiro=gtk3 -j8

It has successfully compiled lucia, so I launch it. It works, but in the driver settings I only have ["OpenGL 3.2", "OpenGL 2.0", "XShm", "None"] for video, ["Alsa", "OSS", "None"] for audio, ["Xlib", "None"] for input.

SDL, Pulseaudio, udev, OpenAL and others drivers are missing.

**Comment by Screwtapello** [comment]
ares tries to build (to pick an example) the Pulseaudio driver if it the file `/usr/lib/x86_64-linux-gnu/libpulse.so` exists (assuming you're on an x86_64 machine). That's where Debian-derived distros put library files. However, [the Arch package](https://archlinux.org/packages/extra/x86_64/libpulse/files/) stores the library as `/usr/lib/libpulse.so` so ares doesn't find it.

**Comment by near-san** [comment]
I'm still not quite ready to make this use the actual pkg_check due to the FreeBSD speed issue. But for now I've updated the command to check both directories instead of just one. I hope this will work for the time being. Will be in v119.1 later today or tomorrow.

**Comment by near-san** [comment]
v119.2 is out now.

**Comment by Mastergatto** [comment]
Thank you for your hard work!

**Comment by Mastergatto** [comment]
I have to bring bad news, v119.2 still doesn't detect those libraries.
May I bring forward an alternative solution?

```
pkg_check1 = $(shell test -e /usr/lib/lib$1.so && echo 1)
pkg_check2 = $(shell test -e /usr/lib/$(shell uname -m)-linux-gnu/lib$1.so && echo 1)
pkg_check = $(if $(filter 1,$(call pkg_check1,$1) $(call pkg_check2,$1)), $2)
```
