### ISSUE TITLE
SEGA Mega-Drive - Ultra Core: Background Graphics flickering

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#45]
NAME: Ultra Core
REGION:  (Japan) (En) (Aftermarket)
SHA-1: A7ECAC360C0588CB8D4866D2593CA0C94BD6CD00
CRC32: AE7FDA5A
MD5: 42781A2D30441E259CEC4B4A4EE10097
ARES VERSION: 119

Some of the game background graphics displayed incorrectly.
See attached video.

https://user-images.githubusercontent.com/78635953/113415393-c94d6680-93c7-11eb-9dcc-c0e8f0ba42e8.mp4

**Comment by HeroponRikiBestest** [comment]
As of Ares 120.7, this issue has been fixed.

**Comment by Yotamtamtam** [comment]
Thank you!
