### ISSUE TITLE
SEGA Mega-Drive - Lemmings 2: The Tribes: Game wont boot

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#46]
NAME: Lemmings 2: The Tribes
REGION: US
SHA-1: 1DE84F5C9B25F6AF4C2C3E18BB710B9572FC0A10
CRC32: DE59A3A3
MD5: 95BC829E8A054853CA2F953A68DC531D
ARES VERSION: 119

The Game wont boot and Ares will display a black screen.
See attatched image.
![Lemmings](https://user-images.githubusercontent.com/78635953/113419750-c014c780-93d0-11eb-84d7-479bb368b557.png)

**Comment by near-san** [comment]
I spent many many hours on this today, but I've not been able to fix it yet.

ares is triggering a fourth Hblank IRQ before a RAM address gets cleared, which causes the game to get stuck in an infinite loop, whereas Mednafen seems to execute another 4000 or so instructions before it reaches its fourth Hblank IRQ. I can't imagine my timing is off by that much, so I'm really not sure what else to try.

**Comment by Yotamtamtam** [comment]
Thank you!
