### ISSUE TITLE
SEGA Mega-Drive - Lemmings: Graphical corruption/flickering

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#47]
NAME: Lemmings 
REGION: EUROPE
SHA-1: F4B86031E348EDB4DCFFAF969998F368955828CE
CRC32: 6A1A4579
MD5: 0B00509E9857CB97243E9F2741E90DE1
ARES VERSION: 119

Some of the game  graphics displayed incorrectly.
See attached video.

https://user-images.githubusercontent.com/78635953/113420905-d2900080-93d2-11eb-8069-26b62e662bec.mp4

**Comment by near-san** [comment]
This will be fixed in v120 for the accuracy renderer, and is good as of now (v119.11)
I'll see once that renderer is finished if I can port some of the improvements back to the scanline renderer.

**Comment by Yotamtamtam** [comment]
Thank you!
