### ISSUE TITLE
Nintendo 64: General: Up,Down,Left & Right Keys wont respond

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#48]
Up,Down,Left & Right Keys wont work in N64 games.

Titles I have tired to play:
- Banjo-Kazooie (U) (Rev A)
- Legend of Zelda, The - Majora's Mask (U)
- Legend of Zelda, The - Ocarina of Time (U) (V1.2)

Tested on Ares 
119 on Microsoft Windows 10 Home
Version: 10.0.19042 Build 19042
Inspirion 7577. x64 based PC
I7-7700hq @ 2.80 GHz

![N64](https://user-images.githubusercontent.com/78635953/113421829-66160100-93d4-11eb-9a86-ab78aeba09ee.png)

**Comment by near-san** [comment]
You have to use the analog stick in those games. Try Namco Museum, it's a game that allows D-pad input.

**Comment by Yotamtamtam** [comment]
I understand. I have tried Namco Museum and it's working. 
Even so, for some reason, I can't use these keys within my laptop keyboard on those specific games. 
Moreover, the L-R buttons dosent work as well, meaning i can't move the character in the game.

**Comment by near-san** [comment]
Those games don't support using the D-pad to move around. You need to use the analog sticks for them.

**Comment by Yotamtamtam** [comment]
So i cannot use just a pc keyboard?

**Comment by Yotamtamtam** [comment]
Fixed. Added keyboard-mapping for all Nintendo 64 controls in ares v120
