### ISSUE TITLE
SEGA Mega-CD - Popful Mail: game crashes after pressing start button

### ISSUE THREAD

**Issue by ghost** [ares-emu/ares#52]
NAME: Popful Mail
REGION: USA
ARES VERSION: 119.2

Game crashes  and display an error message after pressing the start button
See attatched images

![POP_00](https://user-images.githubusercontent.com/78635953/113456671-8797dc80-9416-11eb-891c-610b243aa1f3.png)
![POP_01](https://user-images.githubusercontent.com/78635953/113456667-8666af80-9416-11eb-9e0f-186e42bed0fd.png)

**Comment by near-san** [comment]
Man, this game I swear ... multiple extreme bugs in the Japanese version that we finally got all fixed and now more in the US version >_>
