### ISSUE TITLE
Update the README to clarify the status of this repository

### ISSUE THREAD

**Issue by Screwtapello** [ares-emu/ares#8]
My current plans:

  - ares' development branched from higan after v110; I have converted these to an "ares" branch of the existing higan repository
  - I intend to merge the ares branch back into higan's master branch, creating one code-base with the best of both branches, and with development-history intact
  - I intend to leave this repository as-is, for people who really want to use ares under the ISC licence instead of higan's GPLv3
      - Maybe this repo should be archived to make the status clear?
      - Maybe this repo should be rewritten to contain ares development history?
      - Maybe this repo should be rewritten to contain the full development history including higan and bsnes?
  - The development history currently in the README should be moved somewhere more appropriate

**Comment by jbo-85** [comment]
> Maybe this repo should be archived to make the status clear?

That'd sadly prevent bug-fixes. I'll always dual-license my contributions.
Maybe you can create a separate default branch with a clarification like you did on the old gitlab repo?

> Maybe this repo should be rewritten to contain the full development history including higan and bsnes?

That'd have my vote.

**Comment by Screwtapello** [comment]
Right now, ares' development is recorded as a Git branch named "ares" in the higan repo: https://github.com/higan-emu/higan/tree/ares just in case anybody wanted it for analysis purposes, or to make an ISC-licensed fork.

Putting a clarification/context README in the default branch, and keeping the history in a different branch seems like a good plan, thanks for bringing it up. I've got a lot of higan/ares cleanup work to do, and a big backlog of issues and PRs to review, but this is definitely on my list.

**Comment by Screwtapello** [comment]
I have pushed three new branches to this repository:

  - [original](https://github.com/ares-emu/ares/tree/original)'s current state is exactly that of the official ares v115 source tarball, and the commit history stretches back through ares WIPs into higan and bsnes history (the same ares commit history I stitched together for the higan repo)
  - [with-fixes](https://github.com/ares-emu/ares/tree/with-fixes) is based on "original" and adds the ISC-licensed fixes that were previously merged into the old master branch of this repo
      - there were a couple of PRs that I manually merged into the higan repo that have not landed on the with-fixes branch, but I'm not going to fuss about them if nobody else does
  - [readme](https://github.com/ares-emu/ares/tree/readme) contains only a `README.md` that links to and explains the purpose of the other two branches

If nobody objects or has suggestions within a couple of days, my intent is to make "readme" the new default branch (so it shows up when people visit the repo on GitHub) and delete the current "master" branch (since the fixes are already on "with-fixes" and it doesn't have the historical record the others have).

**Comment by Kawa-oneechan** [comment]
Sounds good to me.

**Comment by Screwtapello** [comment]
Change complete.
