### ISSUE TITLE
SEGA Mega-Drive - The Addams Family: Black section next to the game graphics

### ISSUE THREAD

**Issue by Yotamtamtam** [ares-emu/ares#9]
NAME: The Addams Family
REGION: USA
SHA-1: 1CD7AC493A448C7486EEFDE2300240C3675986A9
CRC32: 71F58614
MD5: EBA5F964ADDEA18B70336D292A08698D
ARES VERSION: 118

The game graphics tend to the left side while on the right side of the screen there is a black part
See attached image.

![MD_ADAMS_INT](https://user-images.githubusercontent.com/78635953/110216150-2e3f9a80-7eb6-11eb-9599-0a3212d32ce3.png)
![MD_ADAMS_IG](https://user-images.githubusercontent.com/78635953/110216148-2d0e6d80-7eb6-11eb-9e72-1c212c1c42eb.png)

**Comment by near-san** [comment]
Same bug as Lunar, it's fixed now.
